### PR TITLE
Add Alpaka `TAcc` to inferface of functors

### PR DESCRIPTION
**Pull request by SimeonEhrig**
- Changed interface of transform and reduce functor
- transform: func(TData i) -> func(TAcc const &acc, TData i)
- reduce: func(TData i, TData k) -> func(TAcc const &acc, TData i, TData k)

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
ping @psychocoderHPC

**Review by sbastrakov — APPROVED** [review]

**Comment by bernhardmgruber** [comment]
I thought Vikunja will provide an STL compatible interface? By adding the accelerator object to the function sinatures that is no longer the case. But I can see the need for that becaues alpaka.

**Comment by SimeonEhrig** [comment]
Originally, I planed to make the Acc object optional but I don't know how. Maybe it is coming back in the future if I have more experience.

**Comment by sbastrakov** [comment]
In PIConGPU we sometime have algorithms that accept two forms of functors. Internally we check which form is callable and call it via some SFINAE.

**Comment by bernhardmgruber** [comment]
> In PIConGPU we sometime have algorithms that accept two forms of functors. Internally we check which form is callable and call it via some SFINAE.

I think this could be a great way to improve the interface. But maybe that's beyond the scope of this PR. @SimeonEhrig let's revisit this at some point in the future.

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
