### PR TITLE
Test file for testing CI with forked repos

### PR DESCRIPTION
**Pull request by SimeonEhrig**
DO NOT MERGE!

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
@bernhardmgruber I know, that drafts avoiding merging, but at the moment I test a bot, which triggers the GitLab CI. Please don't change the type of the PR.

**Comment by bernhardmgruber** [comment]
> @bernhardmgruber I know, that drafts avoiding merging, but at the moment I test a bot, which triggers the GitLab CI. Please don't change the type of the PR.

Ah ok, I see! Please just indicate that next time! I thought you might not know Draft PRs.

**Comment by SimeonEhrig** [comment]
> > @bernhardmgruber I know, that drafts avoiding merging, but at the moment I test a bot, which triggers the GitLab CI. Please don't change the type of the PR.
> 
> Ah ok, I see! Please just indicate that next time! I thought you might not know Draft PRs.

Yes, I had should do this. But this is just special, which hopefully will never happens again ;-)

**Comment by SimeonEhrig** [comment]
Now, the bot is working like expected :-)

**Pull request closed without merging**
