### PR TITLE
Tranform text to paths in the vikunja logo

### PR DESCRIPTION
**Pull request by SimeonEhrig**
Addresses issue #74

### CODE REVIEW

**Review by j-stephan — APPROVED** [review]

**Comment by j-stephan** [comment]
Out of interest, where would I get the `UnDinaru` font? My package manager does not seem to have something suitable.

**Comment by SimeonEhrig** [comment]
> Out of interest, where would I get the `UnDinaru` font? My package manager does not seem to have something suitable.

You can install it via apt: `apt install fonts-unfonts-core`
Before you do it, can you verify it on your computer. I will also do it on my smartphone.

**Comment by SimeonEhrig** [comment]
On my smartphone, it looks fine.

**Comment by j-stephan** [comment]
`vikunja_logo.svg` looks great!

**Pull request merged**
